package com.milyonergame;

///////////////////////////////////////////////
// Melih Akalan, Kim Milyoner Ister App DB
// 18.01.14 03:44
///////////////////////////////////////////////

public final class QuestionDB
{
	private static final int iCount = 159;
	
	public static final int getCount()
	{
		return iCount;
	}
	
	public static final boolean checkAnswer(int q_index, int answer)
	{
		return (iA[q_index] == answer);
	}
	
	public static final String getQuestion(int q_index)
	{
		return sQ[q_index];
	}
	
	public static final String getAnswer(int q_index, int a_index)
	{
		return sA[q_index][a_index];
	}
	
	public static final int getCorrectAnswer(int q_index)
	{
		return iA[q_index];
	}
	
	private static final String sQ[] =
	{
		"Talim yaparken kullanýlan gevþek ok yayýna ne ad verilir?",
		"Hangisi parmak ucunda yürüyen hayvanlardan biridir?",
		"6 aðustos 1945'te ilk atom bombasýný Hiroþima'ya atan Enola Gay uçaðý adýný hangisinden alýr?",
		"Hangi sebzenin tazesi için çiçeði burnunda sözü kullanýlýr?",
		"Gelotoloji adlý bilim dalýnýn konusu nedir?",
		"800'ün üzerinde dilin konuþulduðu ada ülkesi hangisidir?",
		"Manhattan Projesi'nin yöneticisi olarak ilk atom bombasýný yapan, '1945'ten beri baþým aðrýyor' sözünün sahibi fizikçi kimdir?",
		"TBMM yaz tatilinden sonra genellikle hangi tarihte çalýþmalara baþlar?",
		"Kerpeten kelimesi Arapça hangisinden türemiþtir?",
		"Kanaryalarýn kesintisiz ve uzun ötüþleri hangi isimle anýlýr?",
		"Osmanlý'da kullanýlan bir yolcunun 8 saatte gidebileceði mesafeyi karþýlayan uzunluk ölçüsü hangi isimle anýlýr?",
		"Tarýk Bin Ziyad'ýn adý verilen Cebelitarýk Boðazý'ndaki Cebel nedir?",
		"Eskiden 'Haric-i kýsmet' denilen, Atatürk tarafýndan bugünkü ismi verilen terim, hangi matematiksel iþlemin sonucuyla ilgilidir?",
		"Týp tarihinde hangisi diðerlerinden daha önce bulunmuþtur?",
		"Ýp cambazlarýnýn dengeyi saðlamak için kullandýklarý uzun sýrýk hangi isimle anýlýr?",
		"Nüfus Cüzdanlarýna kaç yaþýndan sonra fotoðraf koyulmasý zorunludur?",
		"Gandhi'nin pasif direniþçilerin ailelerinin bakýmý için Güney Afrika'da kurduðu çiftlik hangi edebiyatçýnýn adýný taþýyordu?",
		"Menkul kýymetler sözündeki menkul kelimesinin anlamý nedir?",
		"Er Wojtek hangi hayvandýr?",
		"Makarna yapmak için su kaynatýyorsanýz normal þartlarda hangi þehirdeki su daha düþük sýcaklýkta kaynar?",
		"Porselen kelimesi adýnýn hangisinden alýr?",
		"Adýný Yunan mitolojisindeki güneþ tanrýsýndan alan element hangisidir?",
		"Shakespeare yazdý, Einstein düþündü ve Atatürk yaptý sözü hangi Amerikan baþkanýna aittir?",
		"Hangi ülkede trafik cezalarý hem ihlalin içeriðine hem de sürücünün gelir durumuna göre kesilir?",
		"Yaþamýnýn son yýllarýnda çok kereler 'Bu kýþ komünizm gelecek' diyen devlet adamý kimdir?",
		"Yapýlan araþtýrmalara göre insanlarýn doðuþtan hangi korkuya sahip olduklarý düþünülmektedir?",
		"Hastalarýn kendilerini iyi hissetmelerini saðlamak için verilen hiçbir etkisi olmayan ilaçlarýn adý olan Plasebo'nun latince anlamý nedir?",
		"Mýsýr mitolojisinde tanrý Anubis, ölülerin günahlarýný tartmak için terazinin bir kefesine kalplerini koyarken diðerine ne koyardý?",
		"Hangisinin vücudunda kemik bulunmaz?",
		"Adýnýn anlamý Arapça'da Yunan tavuðu, Yunanca'da Fransýz tavuðu, Fransýzca'da ise Hint tavuðu olan hayvanýn bizdeki adý nedir?",
		"Adý Yunanca'da barýþ anlamýna gelen ve barýþýn sembolü olan tanrýça hangisidir?",
		"Osmanlý Devletinin Arap alfabesinden Latin alfabesine geçmesi gerektiðini söyleyen padiþah kimdir?",
		"Ýnsanýn iskelet sisteminde en çok kemik hangisinde bulunur?",
		"David Copperfield romanýnýn yazarý kimdir?",
		"'Ýyilik timsali' sözündeki 'timsal' kelimesinin anlamý nedir?",
		"Avrupa Birliðinin resmi olmayan baþkenti denildiðinde hangi þehir kastedilir?",
		"'Böbürlenmek' kelimesindeki 'böbür' nedir?",
		"Titanik battýðýnda birçok insan ölmüþken kendi vatandaþýnýn kurtulmasýný onur kýrýcý bulup, ömrünün sonuna kadar o kiþiyi dýþlayan ülke hangisidir?",
		"Adýný bir Roma imparatorundan alan ay hangisidir?",
		"Vücüda melatonin hormonu enjekte edilirse dopamin hormonunun salgýlanmasýyla hangi duygu yok olur?",
		"'Bu soruyu feriþtahý gelse cevaplayamaz' cümlesindeki Farsça'dan dilimize geçen Feriþtah'ýn kelime kökeninin anlamý nedir?",
		"Baþbakan Yýldýrým Akbulut'a söylediði 'Nato daðýlýyor, dostunuz ABD güç kaybediyor. Sizin haliniz ne olacak?' cümlesiyle köþe yazarlarýna konu olan devlet baþkaný kimdir?",
		"Arapça'dan dilimize geçen vezne kelimesinin o dildeki anlamý nedir?",
		"Amerikalý bir mimar olan Howard Garns tarafýndan icat edilen tüm dünyada popüler olan oyun hangisidir?",
		"Dünyanýn En Yalnýz Aðacý unvanýnýn sahibi olup bir kamyon çarpmasý sonucu þuanda yerinde olmayan Tenere Aðacý neredeydi?",
		"Aþure kelimesi hangi sayýnýný Arapça'sýndan türetilerek dilimize geçmiþtir?",
		"Giriþinde Mevlana'nýn 'Kulak eðer gerçeði anlarsa gözdür' sözünün olduðu Suskunlar kitabýnýn yazarý kimdir?",
		"Ne kadar çok kanun, o kadar az adalet sözü kime aittir?",
		"Farsça'dan dilimize geçen ve kelime anlamý iplik olan yiyecek hangisidir?",
		"Bilim adamlarýnýn yaptýðý araþtýrmalardaki gözlemlere göre utandýðýnýzda yüzünüzle beraber hangi organýnýz belirgin olarak kýzarýr?",
		"'Ýnsanýn aklý kendine düþman olur mu? Benim aklým bana düþman' sözünün sahibi Seyit Ali Karakteri, Yýlmaz Güney'in hangi filmine aittir?",
		"1903 yýlýnda kurulduðunda kýsa adý BBJK olan Beþiktaþ'ýn o tarihteki adýndaki ikinci B harfinin açýlýmý neydi?",
		"Daktilo kelimesinin türediði Yunanca daktylos'un anlamý nedir?",
		"Hangi ülkede Birleþme Bakanlýðý vardýr?",
		"Yaklaþýk 45 ülkenin ulusal parasýnda yüzü yer alan kiþi kimdir?",
		"Uzayda yazý yazabilmek için ileri teknolojide üretilen malzemeler bulunmadan önce ne tür bir kalem kullanýlmýþtýr?",
		"Ayçiçekleri ve kendi yatak odasý resimleriyle ünlü ressam kimdir?",
		"Amerika ve Avrupada yüzyýllardýr yaygýn olan, kötü olaylarýn baþa gelmesini engellemek için baþvurulan batýl inanç hangisidir?",
		"Eski Yunan mitolojisinde Khronos ne tanrýsýdýr?",
		"2007'de yaklaþýk 10 bin ton tuz kullanarak inþaat edilen, duvarlarý yalamanýn yasak olduðu Tuz oteli hangi ülkede yer alýr?",
		"Tombala oyununda en büyük sayý kaçtýr?",
		"Kibrit kutusunun iki yanýnda bulunan ve kibrit çöpünün alev almasýný saðlayan karýþýmda fosforla beraber hangisinin tozu vardýr?",
		"2013'ün Ekim ayý içerisinde hangi ülke Yüksek Sosyal Mutluluk Bakanlýðý kurduðunu açýklamýþtýr?",
		"1973'te 11 bin metre yükseklikte bir uçakla çarpýþarak dünyanýn en yüksekten uçan kuþu rekoruna adýný yazdýran kuþun cinsi nedir?",
		"Fransýzca'dan dilimize geçen hangi kýyafet ayný zamanda terzi demektir?",
		"Türkiye'de hangi þehir adýný Sezar'dan alýr?",
		"Hangi müzik aleti mucidinin ismini almýþtýr?",
		"NASA'nýn Ekim 1995 tarihinde uzayda yetiþtirmeyi baþardýðý ilk bitki hangisidir?",
		"Hangi ülkenin milli takýmýnýn teknik direktörü 15 yýllýk kariyerinde sadece 1 galibiyet almasýna raðmen, yeni istifa ederek þaþkýnlýk yaratmýþtýr?",
		"Teorisini 'Elinizi 1 dakika sýcak fýrýna koyun, 1 saat gibi gelir, güzel bir kadýnla 1 saat geçirin, 1 dakika gibi gelir' örneðiyle açýklayan kimdir?",
		"Ekonomik ve politik dengeleri dýþ ülkelere baðlý olan ülkeler için kullanýlan Muz Cumhuriyeti terimi hangi yazara aittir?",
		"Hangisi mucidinin adýný taþýr?",
		"Birçok dile Eski Yunancadan geçen elektrik kelimesinin anlamý nedir?",
		"2011 yýlýnda, anlaþma imzaladýðý kalemi kimseye belli etmeden çalarken görüntülenen kiþi hangi ülkenin cumhurbaþkanýdýr?",
		"Aslýnda bir balýk adý olup sonradan bir silaha adýný veren hangisidir?",
		"Arapça anlamý ferahlýkla, rahatlýkla olan kelime hangisidir?",
		"Ýtalyanca'sý focaccia olan yiyeceðin adý Türkçe'ye ne þekilde geçmiþtir?",
		"Türkiye'deki ilk rock and roll topluluðu hangi okulun öðrencileri tarafýndan kurulmuþtur?",
		"Uzaydan dönen, kol ve bacaklarýný kýpýrdatmakta zorluk çeken astronotlarýn kapsülden çýkartýlmasý iþlemine ne ad verilir?",
		"Jules Verne'nin Seksen Günde Devri Alem adlý eserinde kahramanýn yolculuðunu baþlayýp bitirdiði þehir hangisidir?",
		"Bilim adamlarýnýn araþtýrmalarýna göre, parmak izi insanlarla hemen hemen ayný olan hayvan hangisidir?",
		"Hem bir kadýn ismi hem de bir zaman birimi olan ve Arapça'dan dilimize geçen Saniye ne anlama gelmektedir?",
		"Arabalarýn ilk kullanýlmaya baþlandýðý yýllarda araba sahipleri yakýt almak için nereye gitmek zorundalardý?",
		"Kaba, görgüsüz anlamlarýna gelen ve dilimize Rumca'dan geçen 'Hoyrat' kelimesinin anlamý nedir?",
		"Hangisi Roma Ýmparatorluðunda kullanýlan idari ve askeri görevlilerce paylaþýlan bir unvandýr?",
		"Ülkesinde baþbakan oluþundan görevi sonlanana kadar 10 ABD baþkaný eskiden lider kimdir?",
		"Arapça'dan dilimize geçen eczane kelimesinin kökenindeki eczanýn anlamý nedir?",
		"Hristiyanlýkta bulunan yedi ölümcül günah arasýnda kibir, tembellik, açgözlülük, þehvet, kýskançlýk ve öfke dýþýnda hangisi yer alýr?",
		"Rumca'dan dilimize geçen kümes kelimesinin kökeninin anlamý nedir?",
		"Ceremesini çekmek sözündeki ceremenin kelime kökeninin anlamý nedir?",
		"2009'da OECD'nin üye ülkeler arasýnda yaptýðý negatif ve pozitif tecrübeler araþtýrmasýnda ülkemizin 1. sýrada yer aldýðý his hangisidir?",
		"Almanca'da platsch, Japonca'da pota pota Rusça'da kap kap Fransýzca'da plic plic olarak yazýlan ses nedir?",
		"V. yüzyýla ait Apicius Batý dünyasýnda hangi alanda bilinen en eski kitaptýr?",
		"Eski Yunanca'dan gelen anlamý 'On kiþinin baþkaný' olan kelime hangisidir?",
		"Aralýk ayý içinde Küba'da 1959 devriminden bu yana bir ilke imza atýlarak neyin satýþý serbest býrakýlmýþtýr?",
		"Geçtiðimiz günlerde Ýngiltere'de bir cerrahýn adýnýn baþ harflerini ameliyat ettiði hastasýnýn hangi organýna yazdýðý ortaya çýkmýþtýr?",
		"Geçtiðimiz günlerde Hindistan'da Mandela'yý anmak için yaptýrýlan afiþe Mandela yerine yanlýþlýkla kimin fotoðrafý konmuþtur?",
		"Bir asalaðýn hayatýný içinde ya da üzerinde geçirerek yiyecek ve korunma ihtiyacýný saðladýðý organizmaya ne ad verilir?",
		"Geçtiðimiz günlerde hangi ülkede Avrupa Birliði'ne üyelik baþvurusu için yapýlan referandum sonucu ret çýkmýþtýr?",
		"Hangisinin anlamý 'piþmiþ'tir?",
		"Eski Yunanca kökenli olan safsata kelimesinin kökeninin anlamý nedir?",
		"Uzay adamlarýna verilen astronot adýnýn anlamý hangisidir?",
		"1783'te ilk yolcularýnýn bir horoz, bir ördek ve bir koyun olduðu araç hangisidir?",
		"Bilim adamlarýnýn yaptýklarý araþtýrmalara göre köpekler yaygýn olarak sahiplerinin ne yapmalarýndan etkilenerek aynýsýný yaparlar?",
		"Kökü Orta Asya'ya dayanan bir Anadolu geleneðinde, insanlar düðünlerde bereket için gelin ve damadýn üstüne ne atarlar?",
		"Bilim adamlarýnýn, gýdýklandýklarýnda kahkaha attýklarýný ve gýdýklanmaktan hoþlandýklarýný tespit ettikleri hayvan hangisidir?",
		"Geçtiðimiz günlerde kimin 3. Dünya Savaþý'nda yapacaðý konuþmayý hazýrladýðý ortaya çýkmýþtýr?",
		"Adýný Büyük Ýskender'in kýz kardeþinden alan kent hangisidir?",
		"Soðuk Savaþ döneminde, ABD, 'West Ford Projesi' adýyla dünyanýn yörüngesine hangi nesneden 350 milyon adet yerleþtirmiþtir?",
		"Hangi desenli hayvanýn ilk doðduðunda derisinde hiçbir desen yoktur?",
		"Eski Yunancadan gelen 'jimnastik' kelimesinin kökeni olan 'gymnos' ne demektir?",
		"Altýn ve gümüþe sürülerek saflýk derecesini ortaya çýkaran taþýn adý nedir?",
		"2009'da hangi ülkenin gizli servis þefinin eþi, Facebook'ta kocasýnýn iþi ve ailesine ait detaylarý paylaþtýðý için Dýþiþleri Bakanlýðý'ndan büyük tepki görmüþtür?",
		"Geçtiðimiz günlerde Türkiye'den hangisi Unesco 'Somut Olmayan Kültürel Miras' listesine dahil edilmiþtir?",
		"1962 ile 1977 arasýnda ABD'de nükleer füzelerin ateþlenmesi için belirlenen ve hatýrlanmasý için 15 yýl deðiþmeyen þifre neydi?",
		"'Dünyanýn Yarýsý' adýyla anýlan Ýran þehri hangisidir?",
		"1958’te, 'Nobel Edebiyat Ödülü' kazanmasýna raðmen vatandaþlýktan çýkarýlacaðý korkusuyla reddeden Rus yazar kimdir?",
		"'Sezar’ýn hakký Sezar’a' sözü kime aittir?",
		"Hangisi para üzerine resmi basýlan bilinen ilk gerçek kiþidir?",
		"Efsaneye göre çift olarak yaratýlan insanlar kim tarafýndan ayrýlarak hayatlarý boyunca 'ruh eþleri'ni aramakla cezalandýrýlmýþlardýr?",
		"'Onun sayesinde' sözündeki 'saye' nin kelime anlamý nedir?",
		"Bir dönem üretim zor olduðundan altýndan deðerli olan Fransýz Ýmparatoru'nun zenginliðini göstermek için yemek takýmlarýnda kullandýðý bilinen maden hangisidir?",
		"Arapçadan dilimize geçen 'inziva' kelimesinin kökeninin anlamý nedir?",
		"Anlamý 'Günü yaþa' olan 'Carpe Diem' sözü kime aittir?",
		"1998'de ekonomik kriz sebebiyle Rusya öðretmenlerin maaþlarýný ne olarak ödemiþtir?",
		"Sebze mi meyve mi olduðuna karar verilemeyen bir bitkinin hangi özelliðine bakýlarak bilimsel olarak meyve olduðu söylenir?",
		"Çarþamba, perþembe gibi gün isimlerinde görülen ve aslý Farsçada 'þenbe' olan kelime ne demektir?",
		"Ýþaret dilini öðrenen gelen kim, ayakkabýmýn rengi ne gibi sorulara cevep veren, arkadaþlarýna da öðrenmeleri için yardým eden washoe hangi hayvandýr?",
		"19. yüzyýlda, davetlerde sigara içmeye ayrýlmýþ odalara girmeden önce sigara kokusu sinmemesi için giyilen kýyafetin adý neydi?",
		"Norwood Ölçeði neyi ölçer?",
		"Londra'da Imperial Collage'nin yaptýðý araþtýrma, hangi ülkenin AB'ye katýlmasýyla alerjilerin arttýðýný göstermektedir?",
		"2. Dünya Savaþý'nda Almanlarýn iþgali yüzünden hükümetlerini Ýngiltere'ye taþýyan ve bütün bakanlarýný tek bir odada toplayan ülke hangisidir?",
		"Arapçadan dilimize geçen ve anlamý 'akþam eðlencesi' olan kelime hangisidir?",
		"Sokak çocuklarýnýn kurmuþ olduðu ve sivil toplum örgütlerinin desteklediði banka nerededir?",
		"1977'de kaydedilen ve uzayda nereden geldiði belirlenmeyen, yakalayanýn kaðýda aldýðý nottan adýný alan radyo sinyali nedir?",
		"Suyun dýþýna atlayarak kurbaða, ördek, köpek gibi canlýlarý avlayan balýk hangisidir?",
		"Vatikan'ýn 2013'te dinler arasý diyaloðu geliþtirmek adýna resmi olarak açýðý kulüp ne kulübüdür?",
		"Dilimize Farsçadan geçen 'bedava' kelimesinin kökeninin anlamý nedir?",
		"1958'de Gerald Holtom'ýn yaptýðý barýþ sembolü neyi protesto etmek için tasarlanmýþtýr?",
		"Eski Roma'da gladyatör dövüþlerinin yapýldýðý 'arena'nýn kelime anlamý nedir?",
		"Bir tür Kaplýca olan 'Spa' ismini hangisinden almýþtýr?",
		"Hangisi kesildiðinde, insanlar hep birlikte 'Aaaa' diyerek þok olmuþcasýna tepki verirler?",
		"Misafirliðe çocuklarýyla giden anneler, çocuklarýný yaramazlýk yapmamalarý konusunda ne þekilde uyarýrlar?",
		"Ýnsanlarýn, düðünlerde etrafa saçtýklarý dolarlar genellikle ne kadarlýk banknotlardýr?",
		"Kahvehanelerde, tavlayý ters çevirip, pullarla birlikte zarlarý da pul yerine kullanarak oynanan oyun hangisidir?",
		"Geçici dövme olarak kullanýlan kýnalar hangi milletin adýyla anýlýr?",
		"Yönetmenliðini Joshua Michael Stern’in yaptýðý ashton Kutcher’in baþrolde olduðu filmde kimin hayatý anlatýlmaktadýr?",
		"Birine, 'Dört ayak üstüne düþtün' demek yerine hangisi söylense ayný anlama gelir?",
		"Eskiden, annelerin diðer telefonda çocuklarýnýn konuþmalarýný dinlediði, ayný numaraya sahip iki telefon hattý hangi isimle anýlýrdý?",
		"Lüks lambasýyla aydýnlatýlan el arabalarýndai genellikle gecek vakti, yanýnda ayranla satýlan seyyar satýcý yiyeceði hangisidir?",
		"Duygulanan bir insanýn gözlerinden yaþ gelmesini ifade eden sözün doðru söyleniþ biçimi hangisidir?",
		"Hangisinin hem erkeði hem diþisi ayný adla anýlýr?",
		"Geourge Orwell’in yazdýðý '1984' romanýnda, Okyanusa ülkesinin her þeyin en iyisini bilen ve sürekli izleme halinde olan tek liderinin adý nedir?",
		"Küçük kýz çocuklarý, düðünlerde genellikle hangisini yapmakla görevlidirler?",
		"Özellikle küçük þehirlerde, þehir merkezinden genellikle hangi kelimeyle söz edilir?",
		"Eskiden çoðu evde telefon yokken, insanlar genellikle nereye gidip, telefonun kumbarasýna bozuk para koyarak telefon ederlerdi?",
		"Kuzey yönüne bakan biri, sað tarafýna doðru kendi etrafýnda 360 derecelik bir dönüþ yaptýktan sonra hangi yöne bakýyor olur?",
		"Hangisi bir kuruldur?",
		"Orta Çað’da vebadan kaçan bir grup gencin, gittikleri kýrsal yerde anlattýklarý, 10 günü kapsayan kurgu hikayelerinden oluþan Bocaccio’nun kitabý hangisidir?"
	};
	
	private static final String sA[][] =
	{
		{"Tarumar","Rüsva","Azap","Kepaze"},
		{"Kirpi","Tavþan","Kanguru","Fil"},
		{"Pilotun annesi","Kasýrga adý","Ýlk kadýn pilot","Truman'ýn sekreteri"},
		{"Brokoli","Havuç","Salatalýk","Enginar"},
		{"Kahkaha","Gýdýklanma","Sadakat","Kýskançlýk"},
		{"Patagonya","Endonezya","Madagaskar","Papua Yeni Gine"},
		{"Robert Oppenheimer","Richard Feynman","Gustav Hertz","Leonardo Fibonacci"},
		{"1 Eylül", "15 Eylül","1 Ekim","15 Ekim"},
		{"Yengeç kýskacý","Ahtapot vantuzu","Köpek diþi","Kartal pençesi"},
		{"Falso","Makara","Nakarat","Koma"},
		{"Ýstikamet","Merhale","Hat","Meþakkat"},
		{"Sütun","Geçit","Kanal","Dað"},
		{"Toplama","Çarpma","Bölme","Çýkartma"},
		{"Anestezi","Kan Gruplarý","Tansiyon Aleti","Penisilin"},
		{"Terazi","Cetvel","Ýbre","Kanat"},
		{"7","12","15","18"},
		{"Tolstoy","Dostoyevski","Tagore","Andersen"},
		{"Ticari","Deðerli","Taþýnýr","Deðiþken"},
		{"Ayý","Maymun","At","Eþek"},
		{"Sinop","Erzurum","Hatay","Ýzmir"},
		{"Beyaz diþ","Melek kanadý","Deniz kabuðu","Yumurta kabuðu"},
		{"Helyum","Neon","Platin","Fosfor"},
		{"John Kennedy","Franklin Roosevelt","Bill Clinton","Dight Eisenhower"},
		{"Küba","Çin Halk Cumhuriyeti","Danimarka","Finlandiya"},
		{"Celal Bayar","Ýsmet Ýnönü","Cemal Gürsel","Cevdet Sunay"},
		{"Düþme korkusu","Karanlýk korkusu","Aç kalma korkusu","Takip edilme korkusu"},
		{"Ýkna edeceðim","Ümit edeceðim","Memnun edeceðim","Unutturacaðým"},
		{"Kuþ tüyü","Altýn yaprak","Ýncir çekirdeði","Saç teli"},
		{"Kaplumbaða","Köpekbalýðý","Yunus","Yarasa"},
		{"Sülün","Ördek","Hindi","Tavuk"},
		{"Persephone","Aura","Irene","Nemesis"},
		{"2. Abdülhamit","Abdülaziz","5. Mehmet","Vahidettin"},
		{"El","Kol","Bacak","Ayak"},
		{"James Joyce","John Steinbeck","Arthur Conan Doyle","Charles Dickens"},
		{"Heykel","Terazi","Kandil","Bayrak"},
		{"Lüksemburg","Kopenhag","Brüksel","Paris"},
		{"Mitolojik tanrý","Dað adý","Fýrtýna bulutu","Hayvan türü"},
		{"Norveç","Moðolistan","Japonya","Avustralya"},
		{"Ocak","Mayýs","Temmuz","Aðustos"},
		{"Kýskançlýk","Aþk","Korku","Panik"},
		{"Kral","Öðretmen","Melek","Rehber"},
		{"Saddam Hüseyin","Boris Yeltsin","Hüsnü Mübarek","Hafýz Esad"},
		{"Kasa","Pencere","Terazi","Kürsü"},
		{"Puzzle","Sudoku","Rubik küpü","Amiral Battý"},
		{"Sahra Çölü","Çernobil","Everest Tepesi","Nagazaki"},
		{"1","5","10","99"},
		{"Salah Birsel","Ýhsan Oktay Anar","Yusuf Atýlgan","Sezai Karakoç"},
		{"Sokrates","Hannibal","Pisagor","Cicero"},
		{"Kadayýf","Eriþte","Sucuk","Pýrasa"},
		{"Mide","Akciðer","Böbrek","Beyin"},
		{"Duvar","Sürü","Umut","Yol"},
		{"Baðýþ","Bereket","Belediye","Basketbol"},
		{"Ýmza","Tuþ","Parmak","Harf"},
		{"Güney Kore","Birleþik Arap Emirlikleri","Almanya","Çek Cumhuriyeti"},
		{"Kristof Kolomb","Leonardo da Vinci","II. Elizabeth","Gutenberg"},
		{"Kurþun Kalem","Dolma Kalem","Tükenmez Kalem","Divit"},
		{"Van Gogh","Gustav Klimt","Paul Cezanne","Rembrandt"},
		{"Bardak Kýrmak","Kaðýt Yakmak","Tahtaya Vurmak","Eþikten Atlamak"},
		{"Yolculuk","Zaman","Kader","Doðum"},
		{"Hindistan","Bolivya","Birleþik Arap Emirlikleri","Ýsveç"},
		{"80","88","90","99"},
		{"Kireç","Yün","Cam","Kaya"},
		{"Ýsviçre","Ýzlanda","Meksika","Venezuela"},
		{"Kartal","Leylek","Akbaba","Þahin"},
		{"Bluz","Fular","Tayyör","Tunik"},
		{"Sinop","Isparta","Kayseri","Kars"},
		{"Klarnet","Piyano","Obua","Saksafon"},
		{"Þeker pancarý","Patates","Bezelye","Çilek"},
		{"San Marino","Lüksemburg","Litvanya","Tahiti"},
		{"Albert Einstein","Nikola Tesla","Isaac Newton","Thomas Edison"},
		{"William Faulkner","O. Henry","Pablo Neruda","T.S. Elliot"},
		{"Losyon","Giyotin","Baret","Fermuar"},
		{"Ateþ böceðiyle ilgili","Vatozla ilgili","Kehribarla ilgili","Nehirle ilgili"},
		{"Hindistan","Kolombiya","Ýrlanda","Çek Cumhuriyeti"},
		{"Torpido","Roket","Bumerang","Tomahawk"},
		{"Merhaba","Nefes","Miskin","Ýlham"},
		{"Poðaça","Fasulye","Pancar","Fýstýk"},
		{"Galatarasay Lisesi","Robert Koleji","Deniz Harp Okulu","TED Ankara Koleji"},
		{"Ýkinci doðum","Kýþ uykusu","Kozadan ayrýlýþ","Kafesten çýkýþ"},
		{"Londra","Roma","Paris","Madrid"},
		{"Koala","Köstebek","Tembel Hayvan","Sincap"},
		{"Hýzlý","Kýsa","Sessiz","Ýkinci"},
		{"Araba satýcýsýna","Süpermarkete","Petrol rafinerisine","Eczaneye"},
		{"Taþralý","Þair","Çoban","Pehlivan"},
		{"Spiker","Hoparlör","Tribün","Objektif"},
		{"Hugo Chavez","Kim Il-Sung","Ayetullah Humeyni","Fidel Castro"},
		{"Tozlar","Kýsýmlar","Þiþeler","Bitkiler"},
		{"Musriflik","Yalancýlýk","Oburluk","Ýnatçýlýk"},
		{"Uyuma yeri","Kuþ yuvasý","Çatý altý","Tel kutu"},
		{"Suç","Yük","Masraf","Çile"},
		{"Mutluluk","Gurur","Kýzgýnlýk","Üzüntü"},
		{"Köpek havlamasý","Su damlamasý","Saat saniyesi","Kapýya vurma"},
		{"Yemek kitabý","Çocuk kitabý","Büyü kitabý","Avcýlýk kitabý"},
		{"Konsolos","Dekan","Baron","Kont"},
		{"Cep Telefonu","Yeni Otomobil","Ev","Hamburger"},
		{"Böbrek","Kalp","Mide","Karaciðer"},
		{"Denzel Washington","Bill Cosby","Kofi Annan","Morgan Freeman"},
		{"Konak","Köþk","Kulübe","Kale"},
		{"Ukrayna","San Marino","Arnavutluk","Andorra"},
		{"Alerji","Ödem","Kramp","Pýhtý"},
		{"Ehil","Meþhur","Musrif","Latif"},
		{"Evren gözlemcisi","Yýldýz gemicisi","Gökyüzü kaþifi","Uzay askeri"},
		{"Roket","Teleferik","Balon","Denizaltý"},
		{"Hapþýrmak","Esnemek","Göz kýrpmak","Horlamak"},
		{"Ýðde","Darý","Þeker","Nar"},
		{"Ren geyiði","Sýçan","Sincap","Gelincik"},
		{"Vlademir Putin","Kim Jong-Un","Beþar Esad","II. Elibazbeth"},
		{"Delhi","Selanik","Baðdat","Viyana"},
		{"Þemsiye","Sis bombasý","Su balonu","Bakýr iðne"},
		{"Leopar","Zebra","Dalmaçyalý","Zürafa"},
		{"Çýplak","Yalnýz","Kum","Genç"},
		{"Çakýl taþý","Yapý taþý","Mihenk taþý","Foya taþý"},
		{"Japonya","Rusya","ABD","Ýngiltere"},
		{"Lokum","Býyýk","Çay bardaðý","Türk kahvesi"},
		{"12345678","00000000","AAAAAAAA","X"},
		{"Horasan","Tebriz","Þehriyar","Ýstafhan"},
		{"Boris Pasternak","Mihail Þolohov","Aleksandr Soljenitsin","Maksim Gorki"},
		{"Hz. Ýsa","Büyük Ýskender","Jül Sezar","Hz. Ömer"},
		{"I.Elizabeth","Jules Cesar","Napoleon Bonaparte","Büyük Ýskender"},
		{"Zeus","Apollon","Hermes","Metis"},
		{"Rüzgar","Koltuk","Merdiven","Gölge"},
		{"Krom","Bakýr","Pirinç","Alüminyum"},
		{"Gölge","Köþe","Kovuk","Çadýr"},
		{"Horatius","Virgilius","Caligula","Cicero"},
		{"Matruþka bebek","Kürk","Doðalgaz","Votka"},
		{"Lif içermesi","Çekirdeðinin olmasý","Çið tüketilebilmesi","Þekerli olmasý"},
		{"Yedi","Cumartesi","Þafak","Yarýn"},
		{"Þempanze","Koala","Sincap","Ayý"},
		{"Smokin","Trençkot","Salopet","Süveter"},
		{"Duyma Derecesini","Görme derecesini","Ten rengini","Kellik derecesini"},
		{"Polonya","Çek Cumhuriyeti","Macaristan","Romanya"},
		{"Hollanda","Avusturya","Finlandiya","Ýspanya"},
		{"Kumpanya","Curcuna","Panayýr","Müsamere"},
		{"Hindistan","Romanya","Meksika","Brezilya"},
		{"Bingo","Wow","Oh my god","Oh la la"},
		{"Yayýn balýðý","Pisi balýðý","Somon balýðý","Yýlan balýðý"},
		{"Yemek kulübü","Kitap kulübü","Kriket kulübü","Yoga kulübü"},
		{"Rüzgarla gelen","Aðaçtan düþen","Yerden biten","Çiçek açan"},
		{"Vietnam Savaþý","Soykýrým","Nükleer silahlanma","Kore savaþý"},
		{"Kavga","Kum","Kan","Kýlýç"},
		{"Latince bir deyiþ","Mitolojik bir tanrý","Ýtalya’da bir þelale","Belçika’da bir bölge"},
		{"Telefon","Su","Ýnternet","Elektrik"},
		{"Omuz silkerek","Parmak Þýklatarak","Islýk Çalarak","Kaþ göz iþareti yaparak"},
		{"1","10","50","100"},
		{"Satranç","Dama","Asker tavlasý","Kýz tavlasý"},
		{"Hint","Çin","Yunan","Arap"},
		{"Mark Zockerberg","Eric Schmidt","Steve Jobs","Bill Gates"},
		{"Þanslýsýn","Heyecanlýsýn","Meraklýsýn","Korkaksýn"},
		{"Telsiz Telefon","Paralel Telefon","Ankesörlü telefon","Kurulu telefon"},
		{"Çöp þiþ","Midye dolma","Nohutlu Pilav","Balýk Ekmek"},
		{"Gözlerim yeþerdi","Gözlerim yaþardý","Gözlerim yaþerdi","Gözlerim yeþillendi"},
		{"Manda","Öküz","Boða","Koç"},
		{"Sam Amca","Yurttaþ Kane","Büyük birader","Mr. Big"},
		{"Yüzükleri takmak","Kurdele kesmek","Duvak taþýmak","Pasta kesmek"},
		{"Pazar","Mahalle","Muhit","Çarþý"},
		{"Terzi","Berber","Bakkal","Manav"},
		{"Kuzey","Güner","Doðu","Batý"},
		{"Noter","Müsteþar","Encümen","Armatör"},
		{"Ütopya","Decameron","Ulysses","Þibumi"}
	};
	
	private static final int iA[] = 
	{
		3,3,0,2,0,3,0,2,2,1,1,3,2,0,0,2,0,2,0,1,2,0,2,3,0,0,2,0,1,2,2,0,0,3,0,2,3,2,3,1,2,0,2,1,0,2,1,3,1,0,3,1,
		2,0,2,0,0,2,1,1,2,2,3,2,2,2,3,1,0,0,1,1,2,3,0,0,0,2,0,0,0,3,3,0,2,3,1,2,0,0,2,1,0,1,1,3,3,0,1,3,0,1,2,1,
		1,1,3,1,3,2,0,2,3,3,1,3,0,0,3,0,3,3,1,0,3,1,1,0,0,3,0,0,3,0,1,0,2,0,2,1,3,3,3,0,1,0,2,0,1,2,1,0,2,2,3,2,
		0,2,1
	};
}
